name: rnaseq-transcript
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - stringtie=2.0 #use 2.0 once it is done
  - openssl=1.0
  - bioconductor-ballgown=2.12.0
  - gffcompare=0.11.2
