name: rnaseq-transcript
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - stringtie=2.1.2
  - openssl=1.1.1
  - gffcompare=0.11.2
  - r-tidyverse=1.3.0
  - bioconductor-ballgown=2.20.0
  - bioconductor-tximeta=1.6.2